// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Options: typeof import('./src/components/Options.vue')['default']
    Setup: typeof import('./src/components/Setup.vue')['default']
  }
}

export {}
