name: "publish"
on:
  push:
    branches:
      - release

jobs:
  qemu:
    name: build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.30.0

      - name: install pkg
        run: |
          pnpm install
          npm run tauri build
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: |
          ${{ github.workspace }}/src-tauri/target/release/preemptive_app*
          ${{ github.workspace }}/src-tauri/target/release/sslocal*
          retention-days: 1
